# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protos/event.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "event.PutEventRequest" do
    optional :type, :string, 1
    optional :payload, :message, 2, "google.protobuf.Struct"
  end
  add_message "event.EventResponse" do
  end
  add_message "event.GetEventsSinceRequest" do
    optional :type, :string, 1
    optional :id, :int32, 2
  end
  add_message "event.GetEventsSinceResponse" do
    optional :type, :string, 1
    repeated :events, :message, 2, "google.protobuf.Struct"
  end
end

module Event
  PutEventRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("event.PutEventRequest").msgclass
  EventResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("event.EventResponse").msgclass
  GetEventsSinceRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("event.GetEventsSinceRequest").msgclass
  GetEventsSinceResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("event.GetEventsSinceResponse").msgclass
end
