// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/protos/event.proto

package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutEventRequest struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Payload              *_struct.Struct `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PutEventRequest) Reset()         { *m = PutEventRequest{} }
func (m *PutEventRequest) String() string { return proto.CompactTextString(m) }
func (*PutEventRequest) ProtoMessage()    {}
func (*PutEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_410f2b17726f45aa, []int{0}
}
func (m *PutEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutEventRequest.Unmarshal(m, b)
}
func (m *PutEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutEventRequest.Marshal(b, m, deterministic)
}
func (dst *PutEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutEventRequest.Merge(dst, src)
}
func (m *PutEventRequest) XXX_Size() int {
	return xxx_messageInfo_PutEventRequest.Size(m)
}
func (m *PutEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutEventRequest proto.InternalMessageInfo

func (m *PutEventRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PutEventRequest) GetPayload() *_struct.Struct {
	if m != nil {
		return m.Payload
	}
	return nil
}

type EventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_410f2b17726f45aa, []int{1}
}
func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (dst *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(dst, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

type GetEventsSinceRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsSinceRequest) Reset()         { *m = GetEventsSinceRequest{} }
func (m *GetEventsSinceRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsSinceRequest) ProtoMessage()    {}
func (*GetEventsSinceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_410f2b17726f45aa, []int{2}
}
func (m *GetEventsSinceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsSinceRequest.Unmarshal(m, b)
}
func (m *GetEventsSinceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsSinceRequest.Marshal(b, m, deterministic)
}
func (dst *GetEventsSinceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsSinceRequest.Merge(dst, src)
}
func (m *GetEventsSinceRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsSinceRequest.Size(m)
}
func (m *GetEventsSinceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsSinceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsSinceRequest proto.InternalMessageInfo

func (m *GetEventsSinceRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetEventsSinceRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// Replace Struct with Any?
// https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#any
type GetEventsSinceResponse struct {
	Type                 string            `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Events               []*_struct.Struct `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEventsSinceResponse) Reset()         { *m = GetEventsSinceResponse{} }
func (m *GetEventsSinceResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsSinceResponse) ProtoMessage()    {}
func (*GetEventsSinceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_410f2b17726f45aa, []int{3}
}
func (m *GetEventsSinceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsSinceResponse.Unmarshal(m, b)
}
func (m *GetEventsSinceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsSinceResponse.Marshal(b, m, deterministic)
}
func (dst *GetEventsSinceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsSinceResponse.Merge(dst, src)
}
func (m *GetEventsSinceResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsSinceResponse.Size(m)
}
func (m *GetEventsSinceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsSinceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsSinceResponse proto.InternalMessageInfo

func (m *GetEventsSinceResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetEventsSinceResponse) GetEvents() []*_struct.Struct {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*PutEventRequest)(nil), "event.PutEventRequest")
	proto.RegisterType((*EventResponse)(nil), "event.EventResponse")
	proto.RegisterType((*GetEventsSinceRequest)(nil), "event.GetEventsSinceRequest")
	proto.RegisterType((*GetEventsSinceResponse)(nil), "event.GetEventsSinceResponse")
}

func init() { proto.RegisterFile("src/protos/event.proto", fileDescriptor_event_410f2b17726f45aa) }

var fileDescriptor_event_410f2b17726f45aa = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2e, 0x4a, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x2f, 0xd6, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0xd1, 0x03, 0x73, 0x84,
	0x58, 0xc1, 0x1c, 0x29, 0x99, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x88, 0x8a, 0xa4, 0xd2, 0x34,
	0xfd, 0xe2, 0x92, 0xa2, 0xd2, 0x64, 0xa8, 0x22, 0xa5, 0x08, 0x2e, 0xfe, 0x80, 0xd2, 0x12, 0x57,
	0x90, 0xca, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xca, 0x82,
	0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0xc8, 0x90, 0x8b, 0xbd, 0x20, 0xb1,
	0x32, 0x27, 0x3f, 0x31, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x5c, 0x0f, 0x62, 0xac,
	0x1e, 0xcc, 0x58, 0xbd, 0x60, 0xb0, 0xb1, 0x41, 0x30, 0x75, 0x4a, 0xfc, 0x5c, 0xbc, 0x50, 0x63,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x95, 0xac, 0xb9, 0x44, 0xdd, 0x53, 0x21, 0x56, 0x15, 0x07,
	0x67, 0xe6, 0x25, 0xa7, 0xe2, 0xb3, 0x90, 0x8f, 0x8b, 0x29, 0x13, 0x62, 0x17, 0x6b, 0x10, 0x53,
	0x66, 0x8a, 0x52, 0x2c, 0x97, 0x18, 0xba, 0x66, 0x88, 0xb1, 0x58, 0x75, 0xeb, 0x73, 0xb1, 0x81,
	0x3d, 0x5f, 0x2c, 0xc1, 0xa4, 0xc0, 0x8c, 0xcf, 0xb5, 0x50, 0x65, 0x46, 0x53, 0x18, 0xb9, 0x58,
	0xc1, 0x86, 0x0b, 0x59, 0x71, 0x71, 0xc0, 0x02, 0x44, 0x48, 0x4c, 0x0f, 0x12, 0x9e, 0x68, 0x21,
	0x24, 0x25, 0x02, 0x15, 0x47, 0xf5, 0x1f, 0x83, 0x90, 0x3f, 0x17, 0x1f, 0xaa, 0x23, 0x85, 0x64,
	0xa0, 0x2a, 0xb1, 0x7a, 0x5c, 0x4a, 0x16, 0x87, 0x2c, 0xcc, 0xc0, 0x24, 0x36, 0xb0, 0x7b, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x56, 0xe3, 0x45, 0x34, 0xe3, 0x01, 0x00, 0x00,
}
