# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protos/event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/protos/event.proto',
  package='event',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16src/protos/event.proto\x12\x05\x65vent\x1a\x1cgoogle/protobuf/struct.proto\"I\n\x0fPutEventRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12(\n\x07payload\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x0f\n\rEventResponse\"1\n\x15GetEventsSinceRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"O\n\x16GetEventsSinceResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\'\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x17.google.protobuf.Struct2\x94\x01\n\x05\x45vent\x12:\n\x08PutEvent\x12\x16.event.PutEventRequest\x1a\x14.event.EventResponse\"\x00\x12O\n\x0eGetEventsSince\x12\x1c.event.GetEventsSinceRequest\x1a\x1d.event.GetEventsSinceResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_PUTEVENTREQUEST = _descriptor.Descriptor(
  name='PutEventRequest',
  full_name='event.PutEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='event.PutEventRequest.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='event.PutEventRequest.payload', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=136,
)


_EVENTRESPONSE = _descriptor.Descriptor(
  name='EventResponse',
  full_name='event.EventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=153,
)


_GETEVENTSSINCEREQUEST = _descriptor.Descriptor(
  name='GetEventsSinceRequest',
  full_name='event.GetEventsSinceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='event.GetEventsSinceRequest.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='event.GetEventsSinceRequest.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=204,
)


_GETEVENTSSINCERESPONSE = _descriptor.Descriptor(
  name='GetEventsSinceResponse',
  full_name='event.GetEventsSinceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='event.GetEventsSinceResponse.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='event.GetEventsSinceResponse.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=285,
)

_PUTEVENTREQUEST.fields_by_name['payload'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GETEVENTSSINCERESPONSE.fields_by_name['events'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['PutEventRequest'] = _PUTEVENTREQUEST
DESCRIPTOR.message_types_by_name['EventResponse'] = _EVENTRESPONSE
DESCRIPTOR.message_types_by_name['GetEventsSinceRequest'] = _GETEVENTSSINCEREQUEST
DESCRIPTOR.message_types_by_name['GetEventsSinceResponse'] = _GETEVENTSSINCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PutEventRequest = _reflection.GeneratedProtocolMessageType('PutEventRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUTEVENTREQUEST,
  __module__ = 'src.protos.event_pb2'
  # @@protoc_insertion_point(class_scope:event.PutEventRequest)
  ))
_sym_db.RegisterMessage(PutEventRequest)

EventResponse = _reflection.GeneratedProtocolMessageType('EventResponse', (_message.Message,), dict(
  DESCRIPTOR = _EVENTRESPONSE,
  __module__ = 'src.protos.event_pb2'
  # @@protoc_insertion_point(class_scope:event.EventResponse)
  ))
_sym_db.RegisterMessage(EventResponse)

GetEventsSinceRequest = _reflection.GeneratedProtocolMessageType('GetEventsSinceRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETEVENTSSINCEREQUEST,
  __module__ = 'src.protos.event_pb2'
  # @@protoc_insertion_point(class_scope:event.GetEventsSinceRequest)
  ))
_sym_db.RegisterMessage(GetEventsSinceRequest)

GetEventsSinceResponse = _reflection.GeneratedProtocolMessageType('GetEventsSinceResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETEVENTSSINCERESPONSE,
  __module__ = 'src.protos.event_pb2'
  # @@protoc_insertion_point(class_scope:event.GetEventsSinceResponse)
  ))
_sym_db.RegisterMessage(GetEventsSinceResponse)



_EVENT = _descriptor.ServiceDescriptor(
  name='Event',
  full_name='event.Event',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=288,
  serialized_end=436,
  methods=[
  _descriptor.MethodDescriptor(
    name='PutEvent',
    full_name='event.Event.PutEvent',
    index=0,
    containing_service=None,
    input_type=_PUTEVENTREQUEST,
    output_type=_EVENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEventsSince',
    full_name='event.Event.GetEventsSince',
    index=1,
    containing_service=None,
    input_type=_GETEVENTSSINCEREQUEST,
    output_type=_GETEVENTSSINCERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENT)

DESCRIPTOR.services_by_name['Event'] = _EVENT

# @@protoc_insertion_point(module_scope)
